[build-system]
requires=['setuptools>=42.0',"wheel"]
build-backend = "setuptool.build_meta"

[tool.pytest.ini_options]
testpaths = [
    'tests'
    ]

[tool.mypy]
mypy_path = 'source'
ignore_missing_imports = True